-- 코드를 입력하세요
SELECT      CATEGORY
        ,   SUM(S.SALES) AS TOTAL_SALES
FROM        BOOK B
JOIN        BOOK_SALES S
    ON      B.BOOK_ID = S.BOOK_ID
WHERE       SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
AND         SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY    CATEGORY
ORDER BY    CATEGORY
;

